### ISSUE TITLE
Manque amenity-symbols.mss

### ISSUE THREAD

**Issue by MaelREBOUX** [cquest/osmfr-cartocss#33]
Bonjour,

Il semble manquer un fichier '**amenity-symbols.mss**’ sur github. Quand on essaie de lancer Kosmtik cela donne :

```
node /data/osm/kosmtik/index.js serve /data/osm/styles/osmfr/project.mml 
[Core] No usable config file found in /home/osm/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading project from /data/osm/styles/osmfr/project.mml
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/data/osm/styles/osmfr/amenity-symbols.mss'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Loader.BaseLoader.normalizeStylesheet (/data/osm/kosmtik/src/back/loader/Base.js:74:34)
    at Array.map (native)
    at Loader.BaseLoader.postprocess (/data/osm/kosmtik/src/back/loader/Base.js:12:51)
    at Loader.BaseLoader.load (/data/osm/kosmtik/src/back/loader/Base.js:79:10)
    at Project.load (/data/osm/kosmtik/src/back/Project.js:38:23)
    at new ProjectServer (/data/osm/kosmtik/src/back/ProjectServer.js:31:18)
    at PreviewServer.registerProject (/data/osm/kosmtik/src/back/PreviewServer.js:51:33)
```

**Comment by cquest** [comment]
Hummm... il n'y a plus de amenity-symbols.mss depuis pas mal de commit.

Tu es à jour sur les commit ?

**Comment by cquest** [comment]
il restait effectivement dans le .mml qui est obsolète depuis la migration en .yml... je l'ai donc supprimé avec https://github.com/cquest/osmfr-cartocss/commit/49946ad0604c49bc7d045a231c40f02a983d2fad pour éviter la confusion.
