### ISSUE TITLE
Erreur génération du rendu

### ISSUE THREAD

**Issue by Baraganne** [cquest/osmfr-cartocss#54]
Bonjour,
J'ai une erreur lors de la génération de la carte, je n'arrive pas à comprendre pourquoi (base neuve installée aujourd'hui) :

Trace
    at ProjectServer.raise (/root/src/kosmtik/src/back/ProjectServer.js:267:13)
    at /root/src/kosmtik/src/back/ProjectServer.js:81:30
    at /root/src/kosmtik/node_modules/generic-pool/lib/generic-pool.js:283:11
    at loaded (/root/src/kosmtik/node_modules/mapnik-pool/index.js:23:37)
Postgis Plugin: ERREUR:  la colonne « wood » n'existe pas
LINE 4: ...     FROM ( SELECT way,coalesce(tags->'leaf_type',wood) as w...
                                                             ^
HINT:  Peut-être que vous souhaitiez référencer la colonne « planet_osm_polygon.foot ».
in executeQuery Full sql was: 'SELECT * FROM /* landcover */ (SELECT  ST_Snaptogrid(way,0/4) as way, religion, wood,
                        coalesce (aeroway, amenity, wetland, landuse, leisure, military,
                        "natural", power, tourism, highway, man_made, building) as feature
                FROM ( SELECT way,coalesce(tags->'leaf_type',wood) as wood,
                              ('aeroway_' || (case when aeroway in ('apron', 'aerodrome') then aeroway else null end)) as aeroway,
                              ('amenity_' || (case when amenity in ('parking', 'university', 'college', 'school', 'hospital','clinic', 'kindergarten', 'grave_yard','recycling','place_of_worship', 'public_building', 'townhall', 'courthouse', 'police', 'post_office', 'theatre','community_centre','social_facility') then amenity else null end)) as amenity,
                              ('wetland_' || (case when wetland in ('marsh','bog','reedbed','swamp','saltmarsh','mangrove','tidalflat','saltern','wet_meadow') then wetland else null end)) as wetland,
                              ('landuse_' || (case when landuse in ('quarry', 'vineyard', 'orchard', 'cemetery', 'grave_yard', 'residential', 'garages', 'field', 'meadow', 'grass', 'allotments', 'forest', 'farmyard', 'farm', 'farmyard','farmland', 'recreation_ground', 'conservation', 'village_green', 'retail', 'industrial', 'railway', 'commercial', 'brownfield', 'landfill', 'greenfield', 'construction', 'wood', 'school', 'harbour', 'salt_pond','greenhouse_horticulture') then landuse else null end)) as landuse,
                              ('leisure_' || (case when leisure in ('swimming_pool', 'playground', 'park', 'recreation_ground', 'common', 'garden', 'golf_course') then leisure else null end)) as leisure,
                              ('military_' || (case when military in ('barracks', 'danger_area') then military else null end)) as military,
                              ('natural_' || (case when "natural" in ('beach','desert','heath','mud','grassland','wood','sand','scrub','marsh','bare_rock') then "natural" else null end)) as "natural",
                              ('power_' || (case when power in ('station','sub_station','generator','substation','plant') then power else null end)) as power,
                              ('tourism_' || (case when  tourism in ('attraction', 'camp_site', 'caravan_site', 'picnic_site', 'zoo', 'museum') then tourism else null end)) as tourism,
                              ('highway_' || (case when highway in ('services', 'rest_area') then highway else null end)) as highway,
                              ('man_made_' || (case when man_made is not null then man_made else null end)) as man_made,
                              ('building_' || (case when building in ('civic','public') then building else null end)) as building,
                              case when religion in ('christian','jewish') then religion else 'INT-generic'::text end as religion
                        FROM planet_osm_polygon
                        WHERE  (landuse is not null or wetland is not null or leisure is not null or aeroway in ('apron','aerodrome')
                                or amenity in ('parking', 'university', 'college', 'school', 'hospital','clinic', 'kindergarten', 'grave_yard','recycling','place_of_worship', 'public_building', 'townhall', 'courthouse', 'police', 'post_office', 'theatre','community_centre','social_facility')
                                or military in ('barracks','danger_area')
                                or "natural" in ('beach','desert','heath','mud','grassland','wood','sand','scrub','marsh','bare_rock')
                                or power in ('station','sub_station','generator','substation','plant')
                                or tourism in ('attraction','camp_site','caravan_site','picnic_site','zoo','museum')
                                or highway in ('services','rest_area')
                                or man_made in ('wastewater_plant','clearcut','gasometer','reservoir_covered','water_works','works')
                                or building in ('civic','public'))
                              and (coalesce(landuse, wetland, leisure, aeroway, amenity, military, power, "natural", tourism, highway, man_made) is not null
                              or building in ('civic','public'))
                              and way && ST_SetSRID('BOX3D(-3.402823466385289e+38 -3.402823466385289e+38,3.402823466385289e+38 3.402823466385289e+38)'::box3d, 3857)
                        ORDER BY z_order,way_area desc ) as landcover ) as features LIMIT 0'
  encountered during parsing of layer 'landcover' in Layer

**Comment by Baraganne** [comment]
J'ai réussi à régler mon problème précédent (erreur d'import), mais je me retrouve maintenant avec l'erreur suivante : 

Trace
    at ProjectServer.raise (/root/src/kosmtik/src/back/ProjectServer.js:267:13)
    at /root/src/kosmtik/src/back/ProjectServer.js:81:30
    at /root/src/kosmtik/node_modules/generic-pool/lib/generic-pool.js:283:11
    at loaded (/root/src/kosmtik/node_modules/mapnik-pool/index.js:23:37)
Postgis Plugin: ERREUR:  plus d'une ligne renvoyée par une sous-requête utilisée comme une expression
CONTEXT:  fonction SQL « bbbox », instruction 1
in executeQuery Full sql was: 'SELECT * FROM /* water-lines */ (select st_intersection(bbbox(ST_SetSRID('BOX3D(-3.402823466385289e+38 -3.402823466385289e+38,3.402823466385289e+38 3.402823466385289e+38)'::box3d, 3857),0,0,0),way) as way,waterway,disused,lock,coalesce(tags->'name:fr',tags->'int_name',name) as name, case when coalesce(tunnel,covered) in ('yes','true','1') then 'yes'::text else coalesce(tunnel,covered) end as tunnel, tags->'CEMT' as cemt, case when tags->'CEMT'~'V' then 'true' else '' end as cemt_large, case when tags->'motorboat'='yes' then 'motorboat' when tags->'boat'='yes' then 'boat' else 'no' end as boat from planet_osm_line where way && ST_SetSRID('BOX3D(-3.402823466385289e+38 -3.402823466385289e+38,3.402823466385289e+38 3.402823466385289e+38)'::box3d, 3857) AND osm_id>0 AND waterway in ('weir','river','canal','derelict_canal','stream','drain','ditch','wadi') and (bridge is null or bridge not in ('yes','true','1','aqueduct')) order by z_order ) as water_lines LIMIT 0'
  encountered during parsing of layer 'water-lines' in Layer

Pour le coup j'avoue être un peu dépassé par cette erreur.

Merci d'avance

**Comment by Baraganne** [comment]
J'ai réussi à régler mon problème (erreur d'import)
